include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_print: ignore
    cascade_invocations: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    sort_pub_dependencies: ignore
    unreachable_from_main: ignore
