include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    cascade_invocations: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    sort_pub_dependencies: ignore
    unreachable_from_main: ignore
