import 'dart:io';
import 'dart:isolate';

import 'package:hottie/src/script_change.dart';
import 'package:hottie/src/utils/logger.dart';

const _path = '.dart_tool/main_hottie.g.dart';

RelativePaths findTestsInCurrentDirectory() {
  final files = Directory('test').listSync(recursive: true).where((x) => x.path.endsWith('_test.dart')).toList();
  return RelativePaths(files.map((x) => x.path).toSet());
}

Future<RelativePath> generateMain(RelativePaths testPaths) async {
  final resolved = await Isolate.resolvePackageUri(Uri.parse('package:hottie/hottie_insider.dart'));

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED BY hottie');

  buffer.writeln("import '$resolved';");

  for (final (index, uri) in testPaths.uris.indexed) {
    buffer.writeln("import '$uri' as f$index;");
  }

  buffer.writeln('Map<String, void Function()> _tests() => {');

  for (final (index, RelativePath path) in testPaths.paths.indexed) {
    buffer.writeln("'$path': f$index.main,");
  }

  buffer.writeln('};');
  buffer.writeln('Future<void> main() => hottie(_tests);');

  File(_path).writeAsStringSync(buffer.toString());
  logger.fine('Generated $_path with ${testPaths.describe()}');
  return _path;
}
