import 'dart:io';
import 'dart:isolate';

import 'package:hottie/src/script_change.dart';

Future<RelativePath> generateMain(List<String> args) async {
  final files = Directory('test').listSync(recursive: true).where((x) => x.path.endsWith('_test.dart')).toList();
  final resolved = await Isolate.resolvePackageUri(Uri.parse('package:hottie/hottie_insider.dart'));

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED BY hottie');

  buffer.writeln("import '$resolved';");

  for (final (index, file) in files.indexed) {
    buffer.writeln("import '${file.absolute.path}' as f$index;");
  }

  buffer.writeln('Future<void> main() => hottie({');

  for (final (index, file) in files.indexed) {
    buffer.writeln("'${file.path}': f$index.main,");
  }

  buffer.writeln('});');

  File('build/main_hottie.g.dart').writeAsStringSync(buffer.toString());

  return 'build/main_hottie.g.dart';
}
