// GENERATED BY hottie. Do not edit
// ignore_for_file: constant_identifier_names, prefer_relative_imports
import 'package:hottie/hottie_insider.dart';

void _someTestMain() {} // {imports}

enum PackageId {
  some_package, // {packages}
}

enum TestFileId implements TestFile {
  some_test('', _someTestMain), // {tests}
  ;

  const TestFileId(this.uriString, this.testMain);

  @override
  final String uriString;
  @override
  final TestMain testMain;
  @override
  String toString() => name;
}
