// GENERATED BY hottie. Do not edit
// ignore_for_file: constant_identifier_names, prefer_relative_imports
import 'package:hottie/hottie_insider.dart';

void _someTestMain() {} // {imports}

extension PackageNames on PackageName {
  static const hottie = PackageName('hottie'); // {packages}
}

enum TestId implements TestFile {
  someTest('', _someTestMain), // {tests}
  ;

  const TestId(this.uriString, this.testMain);

  @override
  final String uriString;
  @override
  final TestMain testMain;
}
